# GitHub Sponsors configuration
# Uncomment and add your GitHub username when ready to accept sponsorships
# github: [your-username]

# Other funding platforms (optional)
# patreon: your-username
# open_collective: treeple
# ko_fi: your-username
# custom: ["https://your-donation-page.com"]

# This funding configuration supports the Treeple platform development
# and conservation initiatives. Thank you for considering support!
